### ISSUE TITLE
Replaced cartesi/toolchain by debian cross compiler

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator-rom#10]
## Context

The release process requires a specific order starting from `kernel-headers`, then `toolchain` then the rest.
Using a pre-built toolchain with `cartesi` kernel headers will simplify this process.

## Possible solutions

Use the default debian riscv64 cross compiler with `cartesi/linux` headers when the headers are required.
Optionally only the cross compiler when no headers are needed (such as `rom` and `opensbi`).

## Notes

This Issue only makes sense if the `rom` continues to exist as a separate repository.

**Comment by edubart** [comment]
This issue does not make sense anymore because we removed ROM.
